const generateMigrationContent = (versionNumber: number) => `/**
 * This file is auto generated by galaxy-migrations
 */

const migration${versionNumber} = {
    /**
     * The query to execute
     */
    query: "SELECT * FROM c;",
    /**
     * Callback to apply on each item during the migration
     *
     * It must return an Object
     */
    up: (itemBody) => itemBody,
    /**
     * Callback to apply on each item during the rollback
     *
     * It must return an Object
     */
    down: (itemBody) => itemBody,
    /**
     * Version number to apply on each item updated by this migration
     */
    versionNumber: ${versionNumber},
}

module.exports = migration${versionNumber};
`;

export { generateMigrationContent };
